services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n-bluesky
      args:
        - N8N_IMAGE=n8nio/n8n:latest
    image: n8n-bluesky-dev:latest
    container_name: n8n-dev
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - N8N_LOG_LEVEL=debug
      - N8N_USER_FOLDER=/home/node/.n8n
    ports:
      - "5679:5678"
    restart: unless-stopped
